//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archivos.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosMovimiento
    {
        public System.Guid ArchivosMovimientoID { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public byte[] DocumentoFile { get; set; }
        public string NombreArchivo { get; set; }
        public int UsuarioIDCarga { get; set; }
        public System.DateTime MomentoCarga { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
